Grid_File_Path: test_data.csv # 网格数据文件路径

Grid_Length: 1001 #单位:模拟点(数据列数)
Grid_Height: 1001 #单位:模拟点(数据行数)

Time_Step: 0.1 #单位:h
Velocity_Target: 30 #单位:km/h
# Time_Step*Velocity_Target 就是影响距离,这个距离应当远大于Grid_Step,否则就没有扩散效果了

Grid_Step: 0.01 #单位:km
Total_time: 10 #单位:h
